### PR TITLE
remove `Root`

### PR DESCRIPTION
**Pull request by romainmenke**
removes : 

```
Once: root => {
 			root.walkRules(selectorRegExp, rule =>
```

and implements basic Visitor pattern for PostCSS 8.

### CODE REVIEW

**Comment by Semigradsky** [comment]
@romainmenke could you provide some description?

**Comment by romainmenke** [comment]
@Semigradsky updated, I hope it's clear :)

----------

I am not sure anymore why I updated `yarn.lock`.
Should be harmless, but maybe this change should be removed.

**Comment by romainmenke** [comment]
`yarn.lock` was added in https://github.com/csstools/css-blank-pseudo/commit/5e45d5f2c58a62d53fd58eddf7310fdfb566b183

Removed it again here as I think the intention was not to have lock files in this repo.

**Comment by romainmenke** [comment]
Resolved here : https://github.com/csstools/postcss-plugins

**Pull request closed without merging**
